export const exportData = [
  {
    id: 1,
    image: "/icons/explore/image1.png",
    name: "Find your Courses",
    dis: "Explore the Top Courses in Bangalore 2025",
    courses: [
      "MBBS",
      "BDS",
      "BAMS",
      "BHMS",
      "MBA",
      "PGDM",
      "BSc Nursing",
      "BPT",
      "BSc Perfusion Technology",
      "BSc Cardiac Care",
    ],
    bottom: "View all Top Courses in Bangalore",
  },
  {
    id: 2,
    image: "/icons/explore/image2.png",
    name: "Compare your Colleges",
    dis: "Explore 100+ Top Colleges in Bangalore",
    courses: [
      "Akash Group of Institutions",
      "MS Ramaiah Group of Institutions",
      "Christ University",
      "St. Joseph's College (Autonomous)",
      "Mount Carmel College (MCC)",
      "Kristu Jayanti College",
    ],
    bottom: "View all Top Colleges in Bangalore",
  },
  {
    id: 3,
    image: "/icons/explore/image3.png",
    name: "Exams",
    dis: "Details about NEET, JEE and other Exams",
    courses: [
      "NEET-PG",
      "CAT",
      "NEET-UG",
      "JEE Main",
      "COMEDK",
      "PGCET",
      "NATA",
      "GMAT",
      "GATE",
      "ATMA",
    ],
    bottom: "View all Exams",
  },
];
